import { IParams } from '@/models/interfaces';
import { cn } from "@/lib/utils"

import { interFont } from '@/models/font';
export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js'
};
export async function generateStaticParams() {
  return [{ lang: 'en' }, { lang: 'de' }];
}
export default function RootLayout({
  children,
  params
}: {
  children: React.ReactNode;
  params: IParams;
}) {
  return (
    <html
      lang={params.lang}
      className={cn(`relative antialiased scroll-smooth`, interFont.variable)}
    >
      <body>{children}</body>
    </html>
  );
}
