import { Locale } from '../../i18n.config';
import { cn } from '../../lib/utils';

import { interFont } from '../../models/font';
export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js'
};

export default function RootLayout({
  children,
  params
}: {
  children: React.ReactNode;
  params: {
    lang: Locale;
  };
}) {
  return (
    <html
      lang={params.lang}
      className={cn(`relative antialiased scroll-smooth`, interFont.variable)}
    >
      <body>{children}</body>
    </html>
  );
}
